apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-accumulo-client.properties
data:
    accumulo-client.properties: |-
{{- range $key, $val := .Values.accumuloclientproperties }}
      {{ $key }}={{ $val }}
{{- end }}