apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "healthprobe.fullname" . }}
  labels:
{{ include "healthprobe.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "healthprobe.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "healthprobe.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: accumulo-client-properties-volume
          configMap:
            name: {{ .Release.Name }}-accumulo-client.properties
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret  
          args:
            - monitor
            - readprobe
            {{- with .Values.arguments }}
            {{- toYaml . | nindent 12 }}
            {{- end }} 
          volumeMounts:
          - name: accumulo-client-properties-volume
            mountPath: /opt/at/conf/accumulo-client.properties
            subPath: accumulo-client.properties
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
