# Build Accumulo-Testing Repo
trigger: none

pr: 
  branches:
    include:
    - master

jobs:
- job: BuildAccumuloTesting
  displayName: "Build Accumulo Testing"

  pool:
    name: 'build-agent'

  steps:
  
  - task: Maven@3
    displayName: 'Maven Clean and Package'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenVersionOption: 'Path'
      mavenDirectory: '/usr/local/apache-maven-3.6.2'
      mavenSetM2Home: true
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      options: '-P create-shade-jar -D skipTests -D accumulo.version="2.0.0" -D hadoop.version="3.1.2" -D zookeeper.version="3.4.14"'
      goals: 'clean package'      

  - task: Maven@3
    displayName: 'Maven Copy Dependencies'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenVersionOption: 'Path'
      mavenDirectory: '/usr/local/apache-maven-3.6.2'
      mavenSetM2Home: true
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      options: '-Dmdep.stripVersion=true -DincludeArtifactIds=hadoop-client-api,hadoop-client-runtime -Dhadoop.version="3.1.2"'
      goals: 'dependency:copy-dependencies'     

  - task: Bash@3
    displayName: 'List Build Artifacts'
    inputs:
      targetType: 'inline'
      script: |
        ls -lah
        ls -lah target
