# Build Accumulo-Testing Repo and publish the Build Artifacts to Blob Storage

# When changes to any file merges to master, it triggers the pipeline job.
# If we set batch to true, when a build is running, the system waits until the build is completed,
# then queues another build of all changes that have not yet been built.
trigger:
  batch: true
  branches:
    include:
    - master

# Pull Requests don't trigger this pipeline
pr: none

jobs:
- job: BuildAccumuloTesting
  displayName: "Build Accumulo Testing and Upload Build Artifacts to Blob Storage"

  pool:
    name: 'build-agent'

  steps:
  
  - task: Maven@3
    displayName: 'Maven Clean and Package'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenVersionOption: 'Path'
      mavenDirectory: '/usr/local/apache-maven-3.6.2'
      mavenSetM2Home: true
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      options: '-P create-shade-jar -D skipTests -D accumulo.version="2.0.0" -D hadoop.version="3.1.2" -D zookeeper.version="3.4.14"'
      goals: 'clean package'      

  - task: Maven@3
    displayName: 'Maven Copy Dependencies'
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenVersionOption: 'Path'
      mavenDirectory: '/usr/local/apache-maven-3.6.2'
      mavenSetM2Home: true
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      options: '-Dmdep.stripVersion=true -DincludeArtifactIds=hadoop-client-api,hadoop-client-runtime -Dhadoop.version="3.1.2"'
      goals: 'dependency:copy-dependencies'  

  - task: AzureCLI@1
    displayName: 'Upload build artifacts to blob storage'
    inputs:
      azureSubscription: 'MagnaCarta-CI'
      scriptLocation: inlineScript
      inlineScript: |
        echo -e "\nCreating tarball..."
        tar -cvzf $(Build.ArtifactStagingDirectory)/accumulo-testing.tar.gz  target/accumulo-testing-2.0.0-SNAPSHOT.jar  target/accumulo-testing-shaded.jar target/dependency/*.jar conf/* bin/*
        az storage blob upload -f $(Build.ArtifactStagingDirectory)/accumulo-testing.tar.gz -c accumulo-testing -n accumulo-testing-$(Build.BuildNumber).tar.gz --account-name mcinfra
        az storage blob upload -f $(Build.ArtifactStagingDirectory)/accumulo-testing.tar.gz -c accumulo-testing -n accumulo-testing-master.tar.gz --account-name mcinfra
      addSpnToEnvironment: false
      useGlobalConfig: true
      